#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = ["fonttools>=4.60", "brotli"]
# ///
"""Regenerate public/favicon.svg — "digest", underlined, on Michigan blue.

The icon is the footer wordmark at icon scale. It is generated rather than
hand-drawn because the word has to be *eliza* — the site's display face —
and a favicon cannot wait on a webfont: browsers rasterise it before any CSS
runs, and PWA tiles rasterise it with no document at all. So the glyphs are
converted to outlines here and inlined as a single path.

Run after changing the wordmark or the display face:

    uv run scripts/make-favicon.py          # or: python3 scripts/make-favicon.py

Then eyeball the result at 16/24/32 px, not just at full size. Legibility at
tab scale is the whole design constraint, and it is not visible at 512.
"""

from __future__ import annotations

from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "public" / "fonts" / "eliza.woff2"
OUT = ROOT / "public" / "favicon.svg"

WORD = "digest"
BLUE = "#00274c"  # Michigan blue — same value the footer band is pinned to

CANVAS = 512.0
MARGIN = 40.0  # side inset; the word runs nearly edge to edge on purpose
GAP = 22.0  # descender-to-rule gap
RULE = 30.0  # underline weight
RADIUS = 48.0
# Hairline stroke on the glyphs. eliza's thin strokes vanish when a 512px
# master is downsampled to a 16-24px tab icon. Past ~7 the counters in "e"
# and "g" fill in and the word collapses into a bar — 5 is the ceiling that
# still reads as letterforms.
STROKE = 5.0


def layout(font: TTFont) -> tuple[str, tuple[float, float, float, float]]:
    """Draw WORD on the font's baseline; return (svg path data, ink bounds)."""
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    widths = font["hmtx"]

    missing = [c for c in WORD if ord(c) not in cmap]
    if missing:
        raise SystemExit(f"{FONT.name} has no glyph for: {missing}")

    kern: dict[tuple[str, str], int] = {}
    if "kern" in font:
        for table in font["kern"].kernTables:
            kern.update(table.kernTable)

    def run(pen) -> None:
        x = 0
        previous = None
        for char in WORD:
            name = cmap[ord(char)]
            if previous is not None:
                x += kern.get((previous, name), 0)
            glyphs[name].draw(TransformPen(pen, Transform(1, 0, 0, 1, x, 0)))
            x += widths[name][0]
            previous = name

    path_pen = SVGPathPen(glyphs)
    run(path_pen)
    bounds_pen = BoundsPen(glyphs)
    run(bounds_pen)
    if bounds_pen.bounds is None:
        raise SystemExit("no ink — nothing to draw")
    return path_pen.getCommands(), bounds_pen.bounds


def main() -> None:
    font = TTFont(FONT)
    path, (x0, y0, x1, y1) = layout(font)

    scale = (CANVAS - 2 * MARGIN) / (x1 - x0)
    ink_height = (y1 - y0) * scale
    top = (CANVAS - (ink_height + GAP + RULE)) / 2.0
    tx = MARGIN - x0 * scale
    ty = top + y1 * scale
    rule_y = top + ink_height + GAP

    OUT.write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" '
        f'role="img" aria-label="{WORD}">\n'
        f"  <title>digest.law</title>\n"
        f"  <!-- Generated by scripts/make-favicon.py — do not hand-edit.\n"
        f"       {BLUE} is fixed in both themes, as the footer band is. -->\n"
        f'  <rect width="512" height="512" rx="{RADIUS:.0f}" fill="{BLUE}"/>\n'
        f'  <g fill="#ffffff">\n'
        f'    <path transform="translate({tx:.3f} {ty:.3f}) '
        f'scale({scale:.6f} -{scale:.6f})" stroke="#ffffff" '
        f'stroke-width="{STROKE / scale:.1f}" stroke-linejoin="round" '
        f'paint-order="stroke" d="{path}"/>\n'
        f'    <rect x="{MARGIN:.0f}" y="{rule_y:.2f}" '
        f'width="{CANVAS - 2 * MARGIN:.0f}" height="{RULE:.0f}" rx="2"/>\n'
        f"  </g>\n"
        f"</svg>\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
